homeassistant:
  name: Minha Casa2
  latitude: -20.6621
  longitude: -43.7840
  elevation: 867
  #unit_system: metric
  #time_zone: America/Sao_Paulo
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - 192.168.3.0/24
# Loads default set of integrations. Do not remove.
default_config:


# Custom Panels
panel_custom: 
  - name: Spotify
    sidebar_title: Spotify
    sidebar_icon: mdi:spotify
    module_url: "https://open.spotify.com/intl-pt?nd=1" 

#spotify:
#  client_id: ef38b06b78b545578cd2376bcd8314f3
#  client_secret: 6f789190bed74f8f836c289ac978aad7

hacs:
  token: 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

camera:
 - platform: ffmpeg
   name: "Rua Santana"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.124:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Rua Manoel Lemos"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.123:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Portao"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.122:5122/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Garagem"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.80.252:5252/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Fundos"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.80.253:5253/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Entrada"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.20:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Sala/Entrada"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.21:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Sala/Varanda"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.22:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Quarto Bernardo"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.23:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Quarto Brinquedos"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.24:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Cozinha"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.25:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Espaco Gourmet"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.26:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Quarto Casal"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.27:37777/cam/realmonitor?channel=1&subtype=0
 - platform: ffmpeg
   name: "Escritorio"
   input: -f rtsp -rtsp_transport tcp -i rtsp://admin:logistica2019@@@192.168.3.28:37777/cam/realmonitor?channel=1&subtype=0





lovelace:
  resources:
    - url: /local/mini-media-player-bundle.js?v=1.16.8
      type: module

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
sensor: !include sensor.yaml
mqtt: !include mqtts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml