
  canais_sala:
    name: 'Sky da Sala'
    options:
     - A&E
     - A&E HD
     - AMC
     - AMC HD
     - Animal Planet
     - Animal Planet HD
     - Aparecida
     - Arte1
     - Arte1 HD
     - AXN
     - AXN HD
     - Baby TV
     - Band HD
     - Band News
     - Band News HD
     - Band Sports
     - Band Sports HD
     - Bandeirantes
     - BIS
     - BIS HD
     - Boa Vontade TV
     - Boa Vontade TV HD
     - Boomerang
     - Boomerang HD
     - Canal Brasil
     - Canal Brasil HD
     - Canal do Boi
     - Canal Rural
     - Canal Sony
     - Canal Sony HD
     - Cancao Nova
     - Cartoon HD
     - Cartoon Network
     - Cinemax
     - Cinemax HD
     - CNN Espanhol
     - CNN Internacional
     - CNT
     - Combate
     - Combate HD
     - Comedy Central
     - Comedy Central HD
     - Curta!
     - Curta! HD
     - Discovery H&H HD
     - Discovery Channel
     - Discovery Channel HD
     - Discovery Civilization
     - Discovery H&H
     - Discovery Kids
     - Discovery Kids HD
     - Discovery Science HD
     - Discovery Theater HD
     - Discovery Turbo
     - Discovery Turbo HD
     - Discovery Wold HD
     - Disney
     - Disney Channel HD
     - Disney Junior
     - Disney XD
     - DW
     - E!
     - E! HD
     - EPTV Campinas
     - EPTV Campinas HD
     - EPTV Ribeirao Preto
     - EPTV Sao Carlos
     - ESPN
     - ESPN Brasil
     - ESPN Brasil HD
     - ESPN HD
     - ESPN2
     - ESPN2 HD

  canais_quartoc:
    name: 'Sky do QuartoC'
    options:
     - BIS HD
     - E HD