name: Home Assistant

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ha_test:
    name: Home Assistant Check
    strategy:
      matrix:
        channel: [stable, beta, dev]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v2

      - name: 📋 Copy sample configuration for Home Assistant
        run: |
          mkdir ./test_configuration
          cp -f .devcontainer/sample_configuration.yaml ./test_configuration/configuration.yaml
          cp -r ./custom_components ./test_configuration
          sed -i 's/#//g' ./test_configuration/configuration.yaml

      - name: 👷 Setup Home Assistant
        id: homeassistant
        uses: ludeeus/setup-homeassistant@main
        with:
          tag: ${{ matrix.channel }}
          config-dir: test_configuration