name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Run ${{ matrix.checks }}
    strategy:
      matrix:
        checks:
          - pyupgrade
          - black
          - codespell
          - check-executables-have-shebangs
          - check-json
          - requirements-txt-fixer
          - check-ast
          - mixed-line-ending
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        id: python
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: |
          python3 -m pip install pre-commit
          pre-commit install-hooks --config .github/pre-commit-config.yaml

      - name: Run the check (${{ matrix.checks }})
        run: pre-commit run --hook-stage manual ${{ matrix.checks }} --all-files --config .github/pre-commit-config.yaml

  lint-custom:
    runs-on: ubuntu-latest
    name: With bellybutton
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Enable version 3.8 of Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: make requirements

    - name: Add problem matcher
      run: echo "::add-matcher::.github/matchers/bellybutton.json"

    - name: Validation
      run: bellybutton lint

  lint-json:
    runs-on: ubuntu-latest
    name: With JQ
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: make requirements

    - name: Validation
      run: jq -r -e -c . tests/fixtures/*.json