---
default_config:
logger:
  default: error
  logs:
    hacs: debug
    custom_components.hacs: debug
frontend:
  themes: !include_dir_merge_named themes
#hacs:
#  token: CHANGE_ME
#  sidepanel_title: HACS
#  sidepanel_icon: hacs:hacs
#  frontend_repo: "/workspaces/development/repositories/frontend"
#  appdaemon: true
#  experimental: true
#  country: "ALL"
#  release_limit: 5
